Experiment_name: wlasl_joint_motion

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/ddd/data/WLASL_skeleton/train_data_joint_motion.npy
  label_path: /home/ddd/data/WLASL_skeleton/train_label.pkl
  debug: False
  random_choose: True
  random_shift: True
  window_size: 100
  random_mirror: True
  random_mirror_p: 0.5
  normalization: True
  is_vector: True

test_feeder_args:
  data_path: /home/ddd/data/WLASL_skeleton/val_data_joint_motion.npy
  label_path: /home/ddd/data/WLASL_skeleton/val_label.pkl
  random_mirror: False
  normalization: True
  is_vector: True

# model
model: model.dilated_att12.Model
model_args:
  num_class: 2000
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [90,130]

# training
device: [0,1]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 16
test_batch_size: 64
num_epoch: 180
nesterov: True
warm_up_epoch: 20